data:
    input_path: F:\2024-10-19_105240_bb24-2\Fichiers #F:\fourmis\IHS_SPIKE_fourmis24\data\epis_preda
    output_path: F:\fourmis\IHS_SPIKE_fourmis24\results\epis_preda

segment_kernels:
    model_path: models/sam_b.pt
    output_mask_path: None
    device: cpu # cuda
    model_type: vit_b # vit_l
    area_min: 4000
    area_max: 15000
    crop_x_left: 690 
    crop_x_right: 3470
    save_kernels: False # save rgb image for each kernel or not
