data:
    input_path: E:\MS_2024 #F:\fourmis\IHS_SPIKE_fourmis24\data\epis_preda
    output_path: C:\Users\HySpex_user\Documents\Martin\SPIKE_output\MaleSterile_2024  #SOLACE2021 #F:\fourmis\IHS_SPIKE_fourmis24\results\epis_preda

segment_kernels:
    model_path: models/sam_b.pt
    output_mask_path: None
    device: cpu # cuda
    model_type: vit_b # vit_l
    area_min: 1000 # 4000
    area_max: 3750 #15000
    crop_x_left:  400 # 690
    crop_x_right: 1800 #3470
    save_kernels: False # save rgb image for each kernel or not
